# Generated by Django 3.0.1 on 2019-12-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviapi', '0002_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
